### ISSUE TITLE
Emit data to individual client 

### ISSUE THREAD

**Issue by yogesh-acharya** [py-package/masonite-broadcast-client#2]
Sending data to individual client is not possible currently . I request you to add that feature .

**Comment by yubarajshrestha** [comment]
> Sending data to individual client is not possible currently . I request you to add that feature .

Please upgrade your `Broadcast Server`, `Broadcast Client` and `SocketIO Driver for Masonite`

[Change Logs](https://github.com/py-package/masonite-broadcast-client/releases/tag/v2.0.11)
